### PR TITLE
wd_demo: improved messages in console

### PR DESCRIPTION
**Pull request by mlipok**
### Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.<br>
Please ensure you have read and noticed the checklist below.

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [ ] Bugfix (change which fixes an issue)
- [x] Feature (change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

**wd_demo.au3** messages in console were distinguishable from **wd_core.au3** and **wd_helper.au3** only by color

### What is the new behavior?

currently **wd_demo.au3** messages in console are prefixed with `wd_demo.au3: `
This helps to distinguish demo messages from UDF messages

### System under test

Please complete the following information.

- OS: [e.g. Windows 10]
- OS Arch.: [e.g. X64]
- Browser [e.g. firefox]
- Browser version [e.g. 96.0.3]

### CODE REVIEW

**Comment by Danp2** [comment]
I don't see why this change is needed since (as you've already pointed out) you can identify the wd_demo "messages" by color. Technically, you could also use RegEx to locate the lines beginning with the character set [^+-!].

P.S. I see that we are using all four of these prefixes (^, +, -, and !). Is that needed / desirable?

**Comment by mlipok** [comment]
It helps me a lot in understanding what I see in the logs.
This is something like contextuall reading.
In this way I have better focus on messages wd_demo.au3.
I can easily distinguish them from UDF messages.

The same way it should help new commers to easier understand how the code works.

image

**Comment by Danp2** [comment]
Ok, but I don't see how adding "wd_demo.au3" improves the readability of the log. Personally, I would think adding `"ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : "` would be much more beneficial so that they can see which line generated the message and quickly jump to it.

**Comment by mlipok** [comment]
> Personally, I would think adding `"ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : "` would be much more beneficial so that they can see which line generated the message and quickly jump to it.

Thanks.

Take a look on: [F4 Feature](https://github.com/Danp2/au3WebDriver/pull/288/commits/a3934efabe15fe4468d1bc02f9f710473f5d24bb)

**Comment by Danp2** [comment]
> Take a look on: [F4 Feature](https://github.com/Danp2/au3WebDriver/pull/288/commits/a3934efabe15fe4468d1bc02f9f710473f5d24bb)

It isn't clear exactly what you wanted me to see. From what I can see, you can't use the prefixes in combination with @ to get the line jump feature.

**Comment by Danp2** [comment]
Fine. However, some of your changes seem inconsistent. For example --

`ConsoleWrite("> wd_demo.au3: _WD_Startup" & @CRLF)`

vs

`ConsoleWrite("wd_demo.au3: (" &amp; @ScriptLineNumber &amp; ") : URL=" &amp; _WD_Action($sSession, 'url') &amp; @CRLF)`

Shouldn't these be formatted in a similar fashion?

**Comment by mlipok** [comment]
the first are from main fucntions
the other from the `Demos`

**Comment by Danp2** [comment]
🤷‍♂️

**Pull request merged**
