### PR TITLE
Added: _WD_LastHTTPResponse

### PR DESCRIPTION
**Pull request by Danp2**
### Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.<br>
Please ensure you have read and noticed the checklist below.

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [ ] Bugfix (change which fixes an issue)
- [x] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the new behavior?

Please describe the behavior or changes that are being added by this PR.

### Additional context

See #294 

### System under test

Please complete the following information.

- OS: [e.g. Windows 10]
- OS Arch.: [e.g. X64]
- Browser [e.g. firefox]
- Browser version [e.g. 96.0.3]

### CODE REVIEW

**Comment by mlipok** [comment]
I just made som proposals here:
https://github.com/Danp2/au3WebDriver/pull/297

**Comment by mlipok** [comment]
hm... but 
`$_WD_HTTPRESPONSE = ''` must be reset as well as `$_WD_HTTPRESULT = 0`

**Comment by Danp2** [comment]
Sorry, it wasn't clear to me that you wanted to merge those changes into this PR.

**Comment by mlipok** [comment]
I'm not sure if this revert was a good idea.
Is the effect what you intended?

**Comment by Danp2** [comment]
I didn't merge it. Please just submit your changes as a separate PR.

**Comment by mlipok** [comment]
> I didn't merge it. Please just submit your changes as a separate PR.

Are you able to merge it again ?

**Comment by mlipok** [comment]
I do not see that 
[Revert "Added: _WD_LastHTTPResponse (](https://github.com/Danp2/au3WebDriver/commit/67dc9e7b8f8a5545f2bcde4dc8efe69ce218ad11)https://github.com/Danp2/au3WebDriver/pull/295[)"](https://github.com/Danp2/au3WebDriver/commit/67dc9e7b8f8a5545f2bcde4dc8efe69ce218ad11) …

has taken any effect on:
https://github.com/Danp2/au3WebDriver/blob/master/wd_core.au3

**Comment by mlipok** [comment]
> Please just submit your changes as a separate PR.

Should I just add new PR to [MASTER](https://github.com/Danp2/au3WebDriver) ?

**Pull request merged**
