### PR TITLE
_WD_ElementSelectAction - refactoring + better  DemoSelectOptions

### PR DESCRIPTION
**Pull request by mlipok**
It is related to:
https://github.com/Danp2/au3WebDriver/pull/348#discussion_r930290091

### CODE REVIEW

**Comment by mlipok** [comment]
As for now I must do test.

**Comment by Danp2** [comment]
Still waiting on your test results to confirm proper functionality of the refactored code. If this isn't something that you can provide soon, then I will proceed to the other PR and this refactoring can occur at a later time.

**Comment by mlipok** [comment]
wait
will check today

**Comment by mlipok** [comment]
Tested. All is fine.

**Comment by mlipok** [comment]
I have one additionall small fix

**Comment by mlipok** [comment]
When somebody wants to select multiple `<option>` elements then he must to select all which should be selected, and all others should be deselected.
I mean after `multiSelect` $sCommand is used only the give option should be selected.

I had an issue that I had to deselect `--- wybierz adresata ---` option in order to internal website processing will be able to handle the selection
image

**Comment by Danp2** [comment]
> I have one additionall small fix

This is problematic IMO because you've now gone beyond a "refactor". If you agree, then I will modify the target of this PR to be `master` instead of the other pending PR. Then we can further discuss possible changes to the `multiselect` functionality without compromising #348

**Comment by mlipok** [comment]
So I will revert back [MULTISELECT deselectiong others](https://github.com/Danp2/au3WebDriver/pull/350/commits/878d4872a7a4ab9c923eb58f7e99c19bfedc2d9a)
And it is still good.

**Comment by mlipok** [comment]
If you accept this amendment now, wait a moment longer, because I will also make a patch in wd_demo.au3 related to HIDEN status.

btw.
I had a deadline, and I had to deliver a migrated product from IE to FF for today, so I haven't slept for 30 hours.

I'm going to rest and take a peek at our current topics over the weekend.

**Comment by mlipok** [comment]
Take a look on: [DemoStyles() show how hidden status behaves](https://github.com/Danp2/au3WebDriver/pull/350/commits/50a29c63ce428fbbc6c816511f7742748ba2eb6a)

image

**Comment by Danp2** [comment]
This PR is now separate from #348

**Comment by mlipok** [comment]
I plan do to bigger refactoring. As for now I close this PR.

**Pull request closed without merging**
