### PR TITLE
Create wd_downloadManager.au3

### PR DESCRIPTION
**Pull request by AByGCreation**
### Proposed changes

The purpose is to creat a download Manager to get the progress value of a download in any browsers.
For the moment I try with FF

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [x] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [ ] Bugfix (change which fixes an issue)
- [x] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

When you request a file on a distant server, you can download it, but you can't get the progression. 

### What is the new behavior?

By the way in scraping the download tab of FF, you can ! 
It's the best way I found to get this value.

### System under test

- OS: [Windows 10]
- OS Arch.: [X64]
- Browser [geckodriver]
- Browser version [0.7.0]

### CODE REVIEW

**Comment by Danp2** [comment]
Thanks for your submission. A few thoughts / suggestions --

- I'm not sure if this belongs in this UDF. It would need to work across all browsers at a minimum
- Do you think this would be useful to everyone? If not, then maybe it could be included as an example or posted on the wiki
- Have you looked at implementing this using CDP? See [here](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#event-downloadProgress) for some info.

**Comment by mlipok** [comment]
@Danp2  i think that 1 month of awaiting is enough to close in this case.

**Comment by Danp2** [comment]
@mlipok Yes, it should be. However, I plan to leave the PR open for a little bit longer.

**Comment by AByGCreation** [comment]
Hello @Danp2 & @mlipok, sorry for the late in my response. I want to begin by thankful you about the CDP that I did’nt knew. 
To be honest I don’t know if it’s useful for everyone, but your proposal to implement this in the wiki seems to be a good alternative. Have a great day, let me know if I have an action to do in the future like closing this request, or anything else.

**Comment by Danp2** [comment]
@AByGCreation Thanks for your response. I'll close this PR for now.

**Pull request closed without merging**
