### PR TITLE
_WD_ElementSelectAction 'selectedLabels' JS refact

### PR DESCRIPTION
**Pull request by mlipok**
### Proposed changes

refactoring JS for better code maintaince.

### Checklist

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

- [ ] Bugfix (change which fixes an issue)
- [ ] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

hard to move and test in browser Console

### What is the new behavior?

easier JS code maintaince

### Additional context

none

### System under test
not related

### CODE REVIEW

**Comment by Danp2** [comment]
> refactoring JS for better code maintaince.

Some questions / comments about the refactored code --

- You switched from `var` to `let` when declaring variables. Is there some technical reason to do this that makes it better or more efficient? I'm not aware of any.

- The code "expanded" from 5 lines to 11 lines of JS. How does this make it easier to maintain?

- You should rename the script variable and declare it with `local static` so that the StringReplace only occurs once.

**Comment by mlipok** [comment]
> * You switched from `var` to `let` when declaring variables. Is there some technical reason to do this that makes it better or more efficient? I'm not aware of any.

Recently I was studing JS thus I change some of my habbits.
using analogy to AutoIt   `let` is local scope and `var` is global scope


> * The code "expanded" from 5 lines to 11 lines of JS. How does this make it easier to maintain?

["Program are meant to be read by humans and only incidentally for computers and execute" - Donald Knuth, "The Art of Computer Programming"](https://youtu.be/c-kav7Tf834)

recently 'multiSelect' was few time refactored, each time I had to copy the JS to browser console and maintain JS code.
For this reason 'multiSelect' was refactored to use functions and expose SelectElement out of the function.

How it relates to other one like 'selectedLabels' ? I wanted to refactor all other functions to have use the same coding styles and the same variable names.



> * You should rename the script variable and declare it with `local static` so that the StringReplace only occurs once.

Should I also move all other JScirpt templates at top like `$sScript_MultiSelectTemplate` was moved ?

**Comment by mlipok** [comment]
already checked with DemoSelectOptions() from this version: https://github.com/Danp2/au3WebDriver/pull/367/files

**Comment by Danp2** [comment]
>> You switched from var to let when declaring variables. Is there some technical reason to do this that makes it better or more efficient? I'm not aware of any.

> Recently I was studing JS thus I change some of my habbits.using analogy to AutoIt let is local scope and var is global scope

AFAICS, your change had no effect because the variables are scoped at the function level, which is exactly what `var` does within a function. 

> Should I also move all other JScirpt templates at top like $sScript_MultiSelectTemplate was moved ?

I don't think they need to be moved.

**Comment by mlipok** [comment]
> AFAICS, your change had no effect because the variables are scoped at the function level, which is exactly what `var` does within a function.

Technically you are right
however, IMO: taking into account the correctness of coding in JS (something like good coding practice), it should be changed .



> I don't think they need to be moved.

ok

**Review by Danp2 — CHANGES_REQUESTED** [review]
You should rename the script variable and declare it with local static so that the StringReplace only occurs once.

**Comment by mlipok** [comment]
> You should rename the script variable and declare it with local static so that the StringReplace only occurs once.
Done: [Static $sScript_SelectedLabelsTemplate](https://github.com/Danp2/au3WebDriver/pull/376/commits/8bbfe4318fd9aa2fc7852b9534b1ab3137c7fc09)

**Review by Danp2 — APPROVED** [review]

**Pull request merged**
