### PR TITLE
Update chromedriver support

### PR DESCRIPTION
**Pull request by Danp2**
### Proposed changes

Support new release process for Chromedriver

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [ ] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [ ] Bugfix (change which fixes an issue)
- [x] Feature (change which adds functionality)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

See #473 

### What is the new behavior?

- New download location for chromedriver
- Enable 64 bit support

### System under test

Please complete the following information.

- OS: [e.g. Windows 10]
- OS Arch.: [e.g. X64]
- Browser [e.g. firefox]
- Browser version [e.g. 96.0.3]

### CODE REVIEW

**Comment by Danp2** [comment]
## Note
 Once this PR is merged, only Chrome v115 (scheduled to be released in mid-July) and later will be supported.

**Comment by mlipok** [comment]
Wondering if we should support both old and new ?

**Comment by Danp2** [comment]
I considered it, but I didn't see a good way to allow this within the existing implementation. If you have ideas or you want to discuss more, then I suggest moving the discussion to #473

**Comment by mlipok** [comment]
As so far not tested, but looks good.

**Pull request merged**
