### PR TITLE
_WD_UpdateDriver - better error handling

### PR DESCRIPTION
**Pull request by mlipok**
### Proposed changes
This PR is a fix for the issue catched by : [n3wbie](https://www.autoitscript.com/forum/profile/93584-n3wbie/) AutoIt forum member, and [reported here](https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1496813).

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [x] Bugfix (change which fixes an issue)
- [ ] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

If `$sInstallDir` contains incorrect path for example `/` was used instead `\` then _WD_UpdateDriver() function breaks the scripts on:
```autoit
"Z:\!!!_SVN_AU3\UDF_Forum\Other_Members\Official_AutoIt_Forum\WebDriver\wd_helper.au3" (1433) : ==> The requested action with this object has failed.:
$oNameSpace_Install.CopyHere($FileItem, 20)
$oNameSpace_Install^ ERROR
```

### What is the new behavior?
it properly reports error

```autoit
_WD_UpdateDriver: Error = 18 : Extended = 13 : Result = False
```

### Additional context
I work togeher with `n3wbie` to find out where the issue is.
`n3wbie`  after my help desribe the issue in this post:
https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1497385

I was able to replicate it on my side, and thus I was able to make a fix for this UDF function.

### System under test

not related

### CODE REVIEW

**Comment by Danp2** [comment]
Should use an enum for the @extended status codes. 😉

**Comment by mlipok** [comment]
To master and thus to opera

**Comment by Danp2** [comment]
Ok... will you be adding enums or didn't you want to leave it as-is for now.

**Comment by mlipok** [comment]
> Ok... will you be adding enums or didn't you want to leave it as-is for now.

As it is.
Or add this to task list as a post refactoring things to do before relase.

I need to think little more about.

**Pull request merged**
