### PR TITLE
_WD_UpdateDriver() check _WD_DownloadFile() result

### PR DESCRIPTION
**Pull request by mlipok**
Fix for: https://github.com/Danp2/au3WebDriver/issues/197

### CODE REVIEW

**Comment by Danp2** [comment]
@mlipok I'm going to assume that your fix is good since both you and @seadoggie01 tested it. Only issue I can see is that _WD_DownloadFile returns an error code of $_WD_ERROR_NotFound, which is not listed in the header for _WD_UpdateDriver. Either the header needs to be updated or the error code should be set via something like `$iErr = $_WD_ERROR_GeneralError` instead of `$iErr = @error`

**Comment by mlipok** [comment]
Is that all now ?

**Comment by Danp2** [comment]
AFAIK. Out of curiosity, I see `$_WD_ERROR_NoMatch` in the header. Do you happen to know under what conditions this would be triggered?

**Comment by mlipok** [comment]
> Do you happen to know under what conditions this would be triggered?

interesting.... there was a bug in 

```AutoIt
Func _WD_DownloadFile($sURL, $sDest, $iOptions = Default)
	..........
	Local $sData = InetRead($sURL, $iOptions)
	If @error Then $iErr = $_WD_ERROR_GeneralError

	If $iErr = $_WD_ERROR_Success Then
		Local $hFile = FileOpen($sDest, $FO_OVERWRITE + $FO_BINARY)

		If $hFile <> -1 Then
			FileWrite($hFile, $sData)
			FileClose($hFile)

			$bResult = True
		Else
			$iErr = $_WD_ERROR_GeneralError
		EndIf
	Else
		$iErr = $_WD_ERROR_NotFound
	EndIf
	..........
EndFunc   ;==>_WD_DownloadFile
````

as in current `_WD_DownloadFile` implementation $_WD_ERROR_NotFound will never happen.

**Comment by mlipok** [comment]
I'm thinking about this kind of change:

```AutoIt
Func _WD_DownloadFile($sURL, $sDest, $iOptions = Default)
	..........
	Local $sData = InetRead($sURL, $iOptions)
	If @error Then $iErr = $_WD_ERROR_NotFound

	If $iErr = $_WD_ERROR_Success Then
		Local $hFile = FileOpen($sDest, $FO_OVERWRITE + $FO_BINARY)

		If $hFile <> -1 Then
			..........
		Else
			$iErr = $_WD_ERROR_GeneralError
		EndIf
	EndIf
	..........
EndFunc   ;==>_WD_DownloadFile
```

**Comment by Danp2** [comment]
> as in current `_WD_DownloadFile` implementation, the `$_WD_ERROR_NotFound` error will never happen.

Actually, doesn't it first assign $_WD_ERROR_GeneralError and then subsequently assign $_WD_ERROR_NotFound when the If evaluates to False?

AFAICS, your proposed change should be fine. Still curious about `$_WD_ERROR_NoMatch`. 😉

**Comment by mlipok** [comment]
> Actually, doesn't it first assign $_WD_ERROR_GeneralError and then subsequently assign $_WD_ERROR_NotFound when the If evaluates to False?

Oh. I missed it. You're right.

> AFAICS, your proposed change should be fine. 

Take a look: [$_WD_ERROR_NotFound fix](https://github.com/Danp2/au3WebDriver/pull/198/commits/ab19cdfd0168ad921d6d2c23f899231bf2f86ab6)

> Still curious about `$_WD_ERROR_NoMatch`. 😉

?

**Comment by Danp2** [comment]
> Out of curiosity, I see $_WD_ERROR_NoMatch in the header. Do you happen to know under what conditions this would be triggered?

^ This is what I originally wrote above, but you didn't address it. To be clear, I was referring to the header for _WD_UpdateDriver

**Comment by mlipok** [comment]
This could also happen as a result of `_WD_GetBrowserVersion` or `_WD_GetWebDriverVersion`

**Comment by Danp2** [comment]
> This could also happen as a result of _WD_GetBrowserVersion or _WD_GetWebDriverVersion

Those functions return `$_WD_ERROR_NotFound`, which is different from `$_WD_ERROR_NoMatch`

Am I missing something?!

**Comment by mlipok** [comment]
Yeah.
That I am tired today and needed a little more time to understand what you were asking for.

**Comment by mlipok** [comment]
> Out of curiosity, I see `$_WD_ERROR_NoMatch` in the header. Do you happen to know under what conditions this would be triggered?

Was trigered last time here: https://github.com/Danp2/au3WebDriver/commit/a3b1a894eb7238d1e127aba4224dccd57760e1ba#r66697914

**Pull request merged**
