### PR TITLE
Add _WD_GetContext

### PR DESCRIPTION
**Pull request by Danp2**
### Proposed changes

Add function to enable retrieval of current browsing context<br>
Please ensure you have read and noticed the checklist below.

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [ ] Bugfix (change which fixes an issue)
- [x] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

No simple way to determine current browsing context

### What is the new behavior?

`_WD_GetContext` can be used to obtain the current browsing context.

### Additional context

Eliminates need to call `_WD_FrameList`, which requires many calls to webdriver

### System under test

N/A

### CODE REVIEW

**Comment by mlipok** [comment]
how to use result from this function ?

**Comment by Danp2** [comment]
There are several possible uses that immediately come to mind --

- As a parameter to _WD_Window or _WD_FrameEnter
- As a lookup against the array resulting from _WD_FrameList

There are obvious limitations to the first one, but that doesn't mean that this information isn't useful.

**Comment by mlipok** [comment]
I need do some investigation.

**Comment by Danp2** [comment]
Be my guest. FYI, I've already tested the two use cases I mentioned above. 😉

**Comment by mlipok** [comment]
> I've already tested the two use cases I mentioned above

show the testing snippet

**Comment by Danp2** [comment]
I no longer have that code, but it was simple additions to DemoFrames where I wrote the results of `_WD_GetContext` to the console. Comparing these values to the results from `_WD_FrameList` showed that they matched.

Feel free to run your own tests to confirm, but I don't see how the results could differ when the Javascript involved is exactly the same.

**Pull request merged**
