### PR TITLE
SetupEdge - user-data-dir - admin support

### PR DESCRIPTION
**Pull request by mlipok**
### Proposed changes

Add support for runing MS EDGE with elevated to admin 
```autoit
#RequireAdmin
```

### Checklist

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

- [X] Bugfix (change which fixes an issue)
- [ ] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

using SetupEdge with elevation to Admin will hit error

### What is the new behavior?

works properly

### Additional context

https://www.autoitscript.com/forum/topic/210071-webdriver-and-admin-rights

https://www.autoitscript.com/forum/topic/210071-webdriver-and-admin-rights/?do=findComment&comment=1516684

### System under test

MS EDGE

### CODE REVIEW

**Comment by mlipok** [comment]
Should we also add relevant changes for other browsers ?

**Review by Danp2 — CHANGES_REQUESTED** [review]
IMO, this shouldn't be added as "default" functionality just because MSEdge is misbehaving when run under Admin privileges. I would recommend making the following changes --

- Comment out this line by default
- Add a comment block explaining that the line should be uncommented if issues are encountered when running the demo script under Admin privileges.

**Comment by mlipok** [comment]
Maybe check if is admin .. ?

**Comment by Danp2** [comment]
https://github.com/MicrosoftEdge/EdgeWebDriver/issues/80

**Comment by Danp2** [comment]
So this behavior is by design [per Microsoft](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/80#issuecomment-1507921161). Also, further testing has shown that this change doesn't actually fix the issue,

**Pull request closed without merging**
