### PR TITLE
dp_updatedriver : wd_helper.au3 refactoring

### PR DESCRIPTION
**Pull request by mlipok**
### Proposed changes

refactoring to:
https://github.com/Danp2/au3WebDriver/pull/231

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [ ] Bugfix (change which fixes an issue)
- [ ] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

Directly retrieve file version if full path was supplied is outside `_WD_GetBrowserVersion`

### What is the new behavior?
Checking fullpath moved to the inner processing into `_WD_GetBrowserVersion`

### Additional context

take a look: https://github.com/Danp2/au3WebDriver/pull/231

### System under test

Not related

### CODE REVIEW

**Comment by mlipok** [comment]
Taeka a look also for my comment:  `# CONSIDER to add new $_WD_ERROR_NotSupported`

**Comment by Danp2** [comment]
Why a new PR? Couldn't you have added your proposed changes to the existing one?

Also, I would prefer not to maintain a list of supported browsers in the function headers to avoid having to update them if we add more supported browsers. Therefore, my plan was to remove them rather than expand the list.

**Comment by mlipok** [comment]
It is not possible for me
image

**Comment by mlipok** [comment]
I must modify yours https://github.com/Danp2/au3WebDriver/blob/dp_updatedriver/wd_helper.au3
You must accept it it will be automatically move to yours https://github.com/Danp2/au3WebDriver/blob/dp_updatedriver/wd_helper.au3
And thus automatically to: https://github.com/Danp2/au3WebDriver/pull/231

**Comment by mlipok** [comment]
> I must modify yours https://github.com/Danp2/au3WebDriver/blob/dp_updatedriver/wd_helper.au3 You must accept it (morge), and then it will merged to yours https://github.com/Danp2/au3WebDriver/blob/dp_updatedriver/wd_helper.au3 And thus automatically included to: #231

This is how GitHub works

**Comment by Danp2** [comment]
> This is how GitHub works

I think we both agree that neither of us are "experts" at GH. 😀 

FWIW, I am able to add commits to your PR, so I assumed that you could do this as well. It may be because I am the repo owner and have additional rights.

**Comment by mlipok** [comment]
> I think we both agree that neither of us are "experts" at GH. 😀

I agree. We both still learns how to use Github.

> FWIW, I am able to add commits to your PR, so I assumed that you could do this as well. It may be because I am the repo owner and have additional rights.

Becaues you are top level user for this repository.

**Comment by Danp2** [comment]
> These changes were too extensive to be made in comments on your code

Agreed. I was expecting them to appear as a commit to the existing PR. See my comment above. Using Github Desktop, I can target a specific PR.

> Okay. If this is the only change,

I never said that. 😄 I'll need to take a closer look at your proposed changes.

**Comment by mlipok** [comment]
> I am able to add commits to your PR, so I assumed that you could do this as well

Comments? I can also add to yours PR, but I can't directly modify code in yours PR

**Comment by mlipok** [comment]
> > If this is the only change,
> 
> I never said that. 😄 I'll need to take a closer look at your proposed changes.

I was sure that you have few comments, but I just propose what are next "options" in GitHub way of maintaince multilevel PR's

**Comment by Danp2** [comment]
I like your idea of moving the section of code from `_WD_UpdateDriver` to `_WD_GetBrowserVersion`. However, I see a couple of problems in your revised code --

- You reversed the order of checking `FileExists` and `_WD_GetBrowserPath`. Doing it this way can lead to problems. For example, what happens if the working directory contains a file named `chrome`? 

- You changed the logic by removing `Not` from the line `If Not @error Then`, which breaks the functionality.

**Comment by Danp2** [comment]
Closing this as I've applied the changes directly in original PR.

**Pull request closed without merging**
