### PR TITLE
wd_demo: COOKIE aproval message

### PR DESCRIPTION
**Pull request by mlipok**
### Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.<br>
Please ensure you have read and noticed the checklist below.

### Checklist

Put an `x` in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We are here to help!<br>
This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read and noticed the [CODE OF CONDUCT](https://github.com/Danp2/au3WebDriver/blob/master/docs/CODE_OF_CONDUCT.md) document
- [x] I have read and noticed the [CONTRIBUTING](https://github.com/Danp2/au3WebDriver/blob/master/docs/CONTRIBUTING.md) document
- [ ] I have added necessary documentation or screenshots (if appropriate)

### Types of changes

Please check `x` the type of change your PR introduces:

- [x] Bugfix (change which fixes an issue)
- [ ] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (functional, structural)
- [ ] Documentation content changes
- [ ] Other (please describe)

### What is the current behavior?

User may not be able to click on the confirmation message, I mean not able to click before script goes further.

### What is the new behavior?
Check if first DIV element is visible, as it can hide all sub elements in case when COOKIE aproval message is visible
Script waits and shows error on TimeOut

### Additional context

https://github.com/Danp2/au3WebDriver/pull/292#discussion_r848846752

### System under test

NOT RELATED

### CODE REVIEW

**Comment by mlipok** [comment]
I think that similiar checking should be done with `https://demo.guru99.com`

**Comment by Danp2** [comment]
> I think that similiar checking should be added for `https://demo.guru99.com`

I'm not sure this is necessary. I can't even trigger the "cookie message" issue, so it's hard to test. However, I would think that you could write a generic function that accepts session ID, URL, and xpath to locate.

**Comment by mlipok** [comment]
I agree about the change [Logging should default to Info, not Full](https://github.com/Danp2/au3WebDriver/pull/293/commits/80931376b75fa1f69689d06e43586ab7f643feec)

**Comment by mlipok** [comment]
> > I think that similiar checking should be added for `https://demo.guru99.com`
> 
> I'm not sure this is necessary. I can't even trigger the "cookie message" issue, so it's hard to test. However, I would think that you could write a generic function that accepts session ID, URL, and xpath to locate.

I had to ask you, why you don't see the message for `Goolge` and now also about `https://demo.guru99.com`

My every runs shows to me:
image

image

**Comment by mlipok** [comment]
> I think that similiar checking should be added for `https://demo.guru99.com`

just checked and: Yes it must be done.

**Comment by Danp2** [comment]
> My every runs shows to me

I don't get either of those notices.

> just checked and: Yes it must be done.

Maybe you are the only one with this issue. In that case do we really need to solve it? 😆 

> [guru99.com - hidden support](https://github.com/Danp2/au3WebDriver/pull/293/commits/7e357c60590f4baced8501e39d716ece3d548b98)

Please stop just throwing code together and committing it as a "fix". That just leads to these super extended PRs that are difficult to follow and get approved.

**Comment by mlipok** [comment]
> Please stop just throwing code together and committing it as a "fix". 

I do not understand . Please elaborate.

**Comment by mlipok** [comment]
> Maybe you are the only one with this issue. In that case do we really need to solve it?

I'm the one who raises his voice saying it doesn't work, and proposes a solution.
;)

**Comment by Danp2** [comment]
> I'm not sure (my language issue) ... was that a joke ?

Yes, I was (sort of) joking. However, I'd like to better understand why the problem occurs for you and not for me. One possible cause could be geo-location.

**Comment by Danp2** [comment]
> I do not understand . Please elaborate.

It seems to me that you sometimes commit code before it has been tested by you. Then I have to check it, point out any issues, review your subsequent corrections, etc, which can be frustrating for me.

In the latest example above, it seems like you ignored my earlier feedback ("I would think that you could write a generic function that accepts session ID, URL, and xpath to locate.") and just copied / pasted some code to quickly "fix" the issue. Also, I had changed the spelling of "aproval" to "approval" (this may be fixed in a different PR), but your copied code contains the incorrect spelling again.

I apologize if my message was too abrupt. I really try to refrain from allowing my own tendencies of perfectionism to impact others, but sometimes I fail at that. ☹️

**Comment by mlipok** [comment]
> One possible cause could be geo-location.

We should to ask somebody else to test it.

@TheDcoder @seadoggie01 @Sven-Seyfert 
Could you be so nice and test **DemoElements + FireFox** ?

Question is: Do you get COOKIE popup messages to aproove ?

**Comment by mlipok** [comment]
> It seems to me that you sometimes commit code before it has been tested by you. Then I have to check it, point out any issues, review your subsequent corrections, etc, which can be frustrating for me.

Maybe few times.
Sorry for that.
 
> In the latest example above, it seems like you ignored my earlier feedback ("I would think that you could write a generic function that accepts session ID, URL, and xpath to locate.") and just copied / pasted some code to quickly "fix" the issue. 

**I must to take a look again on it tomorrow**..... going to bed.
I marked this STRONGER to focus on it tomorrow (kind of remider for me, not for you)

> Also, I had changed the spelling of "aproval" to "approval" (this may be fixed in a different PR), but your copied code contains the incorrect spelling again.

Sometimes it's the fault of being overlooked, and sometimes it's the fault of not understanding.
Sorry about that.

> I apologize if my message was too abrupt. I really try to refrain from allowing my own tendencies of perfectionism to impact others, but sometimes I fail at that.

Nobody's perfect. Me too, because I have the same habit.

Fortunately, we understand each other, we have patience, and we exchange arguments just by talking. After which we finally find a common path to achieve a common goal, respecting the other person.

This is what it is all about.

Sometimes, however, it takes a little more sacrifice than you would like.
Sorry about that.

**Comment by Danp2** [comment]
No need. I checked with a VPN and confirmed that the cookie / privacy popups appeared when I connected via a different country.

**Comment by mlipok** [comment]
> No need. I checked with a VPN and confirmed that the cookie / privacy popups appeared when I connected via a different country.

Did you also confirm that my modification resolve this issue ?
In other way what next with this PR ?

**Comment by Danp2** [comment]
> Did you also confirm that my modification resolve this issue ?

Nope. I was manually checking the sites after enabling the VPN.

**Comment by mlipok** [comment]
Do you plan to check it over VPN or I should ask again others to check ?

**Comment by Danp2** [comment]
You can see if the others can test it. I'll try to do it as well if I get the chance.

**Comment by Danp2** [comment]
@mlipok I was able to perform some limited tests over the VPN. Your changes work AFAICS. However, I'm not sure that the user will known they need to accept all cookies to continue.

I will submit some changes momentarily where I converted _Demo_NavigateToGoogle into a generic routine.

**Comment by mlipok** [comment]
Good change.

**Comment by mlipok** [comment]
Yahoo needs the same change

**Comment by mlipok** [comment]
all other `_WD_Navigate()` uses websites which not showing COOKIE aproval message.

**Comment by mlipok** [comment]
When you find time you can do finall review and merge.
As for me this is all what I wanted to do here.

**Pull request merged**
